sandbox deploy.yml file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy Help-To-Heat App
+name: Deploy help-to-heat App
 
 env:
   DOCKER_BUILDKIT: 1
@@ -6,8 +6,7 @@ env:
 on:
   push:
     branches:
-      - develop
-      - docker
+      - sandbox
 
 permissions:
   packages: write
@@ -16,7 +15,7 @@ permissions:
   contents: read
 
 jobs:
-  push_help_to_heat_image:
+  push_help-to-heat_image:
     runs-on: ubuntu-latest
 
     env:
@@ -26,6 +25,10 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+
+      - name: Setup prod api host
+        if:  ${{ github.event_name == 'release' }}
+        run: echo "BASE_URL=https://help-to-heat.london.cloudapps.digital" >> $GITHUB_ENV
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v2
@@ -43,8 +46,8 @@ jobs:
           docker build . --file $DOCKER_FILE --tag $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --build-arg BASE_URL=$BASE_URL
           docker push -a $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE
 
-  deploy_help_to_heat_image:
-    needs: [push_help_to_heat_image]
+  deploy_help-to-heat_image:
+    needs: [push_help-to-heat_image]
 
     runs-on: ubuntu-latest
 
@@ -55,7 +58,8 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Get space name
+      - name: Get non-prod space name
+        if:  ${{ github.event_name != 'release' }}
         uses: kanga333/variable-mapper@v0.2.2
         with:
           key: "${{github.ref_name}}"
@@ -65,7 +69,20 @@ jobs:
               "demo": {"CF_SPACE": "demo"},
               "temp": {"CF_SPACE": "temp"},
               "develop": {"CF_SPACE": "develop"},
-              "staging": {"CF_SPACE": "staging"}
+              "staging": {"CF_SPACE": "staging"},
+              "pentest": {"CF_SPACE": "pentest"},
+              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
+            }
+
+      - name: Get prod space name
+        if:  ${{ github.event_name == 'release' }}
+        uses: kanga333/variable-mapper@v0.2.2
+        with:
+          key: "${{github.ref_name}}"
+          map: |
+            {
+              "v?.?.?": {"CF_SPACE": "prod"},
+              "feature/deploy-from-main": {"CF_SPACE": "flibble"}
             }
 
       - name: Download CF CLI
@@ -80,6 +97,17 @@ jobs:
           DOCKER_IMAGE: help-to-heat
           PAT_TOKEN_USER: ${{ secrets.PAT_TOKEN_USER }}
           PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
-        run: CF_DOCKER_PASSWORD="$PAT_TOKEN" ./cf push -f manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$PAT_TOKEN_USER
+        run: CF_DOCKER_PASSWORD="$PAT_TOKEN" ./cf push -f manifests/"$CF_SPACE"/help-to-heat_manifest.yml --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$PAT_TOKEN_USER
 
-      - uses: actions/checkout@v2
+      # - uses: actions/checkout@v2
+      # - name: Slack Notification
+      #   continue-on-error: true
+      #   if: ${{ failure() && github.ref_name == 'prod' || failure() && github.ref_name == 'develop' }}
+      #   uses: rtCamp/action-slack-notify@v2
+      #   env:
+      #     SLACK_COLOR: '#FF0000'
+      #     SLACK_ICON: https://avatars0.githubusercontent.com/u/818058?s=200&v=4
+      #     SLACK_TITLE: '${{ github.ref_name }} deployment ${{ job.status }} :warning:'
+      #     SLACK_USERNAME: ${{ github.actor }}
+      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+      #     SLACK_MESSAGE: '${{ github.ref_name }} Action ${{ job.status }}'
